import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import PastryShopContext from '@/contexts/PastryShopContext';
import { IBakedGoods, IIngredients, IPastriesOnDisplay, IUnlockedRecipes } from '@/types/PastryShop';
import Tab from '@/shared/components/Tab';
import Home from '@/components/Home/Home';
import CookBook from '@/components/CookBook/CookBook';
import Market from '@/components/Market/Market';
import Bakery from '@/components/Bakery/Bakery';
import { ConfigProvider, Image, Layout, Tabs, TabsProps, Typography } from 'antd';
import pastryShopTheme from '@/themes/PastryShopTheme';
import styles from '@/styles/index.module.scss';
import Player from '@/data/Player';
import Storage from '@/data/Storage';
import Recipes from '@/data/Recipes';
import Items from '@/data/Items';

export default function Index() {
  const [playerName, setPlayerName] = useState<string>(Player.name);
  const [playerLevel, setPlayerLevel] = useState<number>(Player.level);
  const [playerCurrentExp, setPlayerCurrentExp] = useState<number>(Player.currentExp);
  const [playerExpToLevel, setPlayerExpToLevel] = useState<number>(Player.expToLevel);
  const [playerCash, setPlayerCash] = useState<number>(Player.cash);
  const [playerRep, setPlayerRep] = useState<number>(Player.rep);
  const [playerDaysPlayed, setPlayerDaysPlayed] = useState<number>(Player.daysPlayed);
  const [storageIngredients, setStorageIngredients] = useState<IIngredients[]>(Storage.ingredients);
  const [unlockedRecipes, setUnlockedRecipes] = useState<IUnlockedRecipes[]>(Player.unlockedRecipes);
  const [unlockedEquipment, setUnlockedEquipment] = useState<string[]>(Player.unlockedEquipment);
  const [bakedGoods, setBakedGoods] = useState<IBakedGoods[]>(Storage.bakedGoods);
  const [pastriesOnDisplay, setPastriesOnDisplay] = useState<IPastriesOnDisplay[]>(Storage.pastriesOnDisplay);
  const [tabHeight, setTabHeight] = useState(0);
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    window.addEventListener('resize', handleResize);
    handleResize();
    return () => window.removeEventListener('resize', handleResize);
  });

  const handleResize = () => {
    if (window.innerWidth <= 767) {
      setIsMobile(true);
    } else {
      setIsMobile(false);
    }
  };

  const onChange = (key: string) => {};

  const tabs: TabsProps['items'] = [
    {
      key: '1',
      label: `Home`,
      children: <Tab component={<Home />} image={'home.png'} isMobile={isMobile} />,
    },
    {
      key: '2',
      label: `Cook Book`,
      children: <Tab component={<CookBook />} image={'cookbook.png'} isMobile={isMobile} />,
    },
    {
      key: '3',
      label: `Market`,
      children: <Tab component={<Market />} image={'market.png'} isMobile={isMobile} />,
    },
    {
      key: '4',
      label: `Bakery`,
      children: <Tab component={<Bakery />} image={'bakery.png'} isMobile={isMobile} />,
    },
  ];

  return (
    <ConfigProvider theme={pastryShopTheme}>
      <Head>
        <title>Little Pastry Shop</title>
        <meta name='a bakery management mini-game about a little pastry shop.' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/little-pastry-shop/icons/cupcake.png' />
      </Head>
      <main>
        <Layout style={{ minHeight: '100vh', backgroundColor: '#FFFFFF' }}>
          <Layout.Header className={styles.header}>
            <Image
              alt='pastry logo'
              height={40}
              width={40}
              src={`/little-pastry-shop/images/pastry-logo.png`}
              style={{ display: 'block', verticalAlign: 'initial' }}
              preview={false}
            ></Image>
            <Typography.Title level={!isMobile ? 2 : 3} style={{ textAlign: 'center', margin: 0 }}>
              {'Little Pastry Shop'.toUpperCase()}
            </Typography.Title>
          </Layout.Header>
          <Layout.Content className={styles.content}>
            <PastryShopContext.Provider
              value={{
                Player,
                Storage,
                Recipes,
                Items,
                playerName,
                setPlayerName,
                playerLevel,
                setPlayerLevel,
                playerExpToLevel,
                setPlayerExpToLevel,
                playerCurrentExp,
                setPlayerCurrentExp,
                playerCash,
                setPlayerCash,
                playerRep,
                setPlayerRep,
                playerDaysPlayed,
                setPlayerDaysPlayed,
                storageIngredients,
                setStorageIngredients,
                unlockedRecipes,
                setUnlockedRecipes,
                unlockedEquipment,
                setUnlockedEquipment,
                bakedGoods,
                setBakedGoods,
                pastriesOnDisplay,
                setPastriesOnDisplay,
                tabHeight,
                setTabHeight,
                isMobile,
              }}
            >
              <Tabs
                defaultActiveKey='1'
                items={tabs}
                centered
                onChange={onChange}
                size='large'
                style={{ maxWidth: '1200px', height: isMobile ? 'auto' : '650px', flexGrow: 1 }}
                className={styles.tabs}
              />
            </PastryShopContext.Provider>
          </Layout.Content>
        </Layout>
      </main>
    </ConfigProvider>
  );
}
